# path:
ckpt_path: "models/LaVie_Base/lavie_base.pt"
output_folder: "./samples/lavie/"

# VAR config:
var_checkpoint_dir: "VAR/"
var_model_depth: 30
imagenet_class: 980

# model config: 
model: UNet
video_length: 16
image_size: [320, 512]

# beta schedule
beta_start: 0.0001
beta_end: 0.02
beta_schedule: "linear"

# model speedup
use_compile: False
use_fp16: True

# sample config:
seed: [0]
run_time: 0
guidance_scale: 3.0
sample_method: 'ddpm'
num_sampling_steps: 50
text_prompt: [
       'A volcano erupting with lava flowing down its sides',
       'A volcano exploding with ash and smoke',
       'A volcano with a crater filled with molten lava',
] 
