# path:
ckpt_path: "/Users/gilliam/Desktop/493G1/VideoVAR/lavie_base.pt"
output_folder: "./samples/lavie/"

# VAR config:
var_checkpoint_dir: "/Users/gilliam/Desktop/493G1/VideoVAR/VAR/"
var_model_depth: 30
imagenet_class: 980

# model config: 
model: UNet
video_length: 16
image_size: [320, 512]

# beta schedule
beta_start: 0.0001
beta_end: 0.02
beta_schedule: "linear"

# model speedup
use_compile: False
use_fp16: True

# sample config:
seed: [0]
run_time: 0
guidance_scale: 7.0
sample_method: 'ddpm'
num_sampling_steps: 50
text_prompt: [
       'A cup and a couch',
       'A person eating a burger.',
] 
